### ISSUE TITLE
Public availability

### ISSUE THREAD

**Issue by laughedelic** [bradleyscollins/try4j#1]
This library looks very interesting. Would be nice to try it in our project. 
Is it in any public repository?

**Comment by md97212** [comment]
Hi Bradley, 

Thanks for publishing this on github, very useful and saved me the time of writing it!

Can you publish this to maven central repository? Otherwise we need to embed the dependencies.
It should be straightforward, http://maven.apache.org/guides/mini/guide-central-repository-upload.html

Mark

**Comment by laughedelic** [comment]
@md97212 thanks for raising this again!
@bradleyscollins yep, the issue actually remains, because the library is not available from some repository. Here are a couple of links:
- about [publishing with sbt to maven central](http://www.theguardian.com/info/developer-blog/2014/sep/16/shipping-from-github-to-maven-central-and-s3-using-travis-ci)
- or to [sonatype](http://www.scala-sbt.org/0.13/docs/Using-Sonatype.html)
- [bintray](https://github.com/softprops/bintray-sbt) is another option

**Comment by bradleyscollins** [comment]
My apologies, guys. I *thought* I published v1.6.0 to Bintray, but perhaps I didn't do something quite right. This is the first open source project I've attempted to publish.

Are the files not available here?

https://bintray.com/bradleyscollins/maven/try4j/1.6.0/view#files

@laughedelic, I *attempted* to follow your pointers to publish to Bintray. Perhaps you'd be willing to take a look at my build.sbt file and let me know if you have any suggestions about what I'm doing wrong. E.g., IntelliJ is complaining about this line:

    seq(bintraySettings:_*)

But the project *appeared* to publish, so I decided it was a fluke.

@md97212, I'm aiming to please here, so I'll try to publish to Maven Central and Sonatype, too. Bintray appears to have a way to sync with Maven Central, but I doubt that's working yet as I haven't set anything up with Maven Central.

**Comment by laughedelic** [comment]
@bradleyscollins hey, sorry, I didn't notice that you've published it to bintray! yes, it works fine, I will make a PR to add instructions to readme :wink: 
About settings in `build.sbt`, try to write just `bintraySettings` (without `seq(...)`), otherwise everything seems fine. And also you don't need that `build.xml`, I guess..

**Comment by laughedelic** [comment]
Done in #3 :ok_hand:

**Comment by md97212** [comment]
fantastic, thanks for the response!

**Comment by laughedelic** [comment]
Everything is cool. So let's close it ")
